version: "3.1"
services:
    web:
        image: php:7.4-apache
        command: >
            /bin/bash -c "
                docker-php-ext-install mysqli;
                apache2-foreground;"
        ports:
            - "5000:80"
        volumes:
            - .:/var/www/html/
        links:
            - db
        networks:
            - php-net
    db:
        image: mysql:8.0
        container_name: mysql-app
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: demo_db
            MYSQL_USER: satish
            MYSQL_PASSWORD: satish
            MYSQL_ROOT_PASSWORD: satish
        volumes:
            - persistent:/var/lib/mysql
        networks:
            - php-net
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        links:
            - db
        ports:
            - "8080:80"
        environment:
            PMA_HOST: db
        networks:
            - php-net
networks:
    php-net:
        driver: bridge
volumes:
persistent:

